apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-shop
  labels:
    app: mini-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-shop
  template:
    metadata:
      labels:
        app: mini-shop
    spec:
      containers:
        - name: mini-shop
          image: rvorbita/mini_shop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
      restartPolicy: Always
