# apiVersion: v1
# kind: Secret
# metadata:
#   name: mini-shop-secret
# type: Opaque
# data:
#   POSTGRES_USER: bWluaV9hZG1pbg==
#   POSTGRES_PASSWORD: c2VjcmV0MTIz
#   POSTGRES_DB: bWluaV19c2hvcA==

apiVersion: v1
kind: Secret
metadata:
  name: mini-shop-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://mini:mini123@mini-shop-db:5432/minishop
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin123
