apiVersion: v1
kind: Service
metadata:
  name: mini-shop-service
  labels:
    app: mini-shop
spec:
  selector:
    app: mini-shop
  type: NodePort
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
      nodePort: 30001
